const Data = [
  {
    Professional_Field: 'Marketing',
    ID: 'MKT',
    value: [
      'General Marketing',
      'Brand Marketing',
      'Content Marketing',
      'Digital Marketing',
      'Email Marketing',
      'Marketing Communications',
      'Marketing Research',
      'Partner Marketing',
      'Product Marketing',
      'Social Media Marketing',
      'All of the above',
    ],
  },
  {
    Professional_Field: 'Marketing',
    ID: 'MKT',
    value: [
      'General Marketing',
      'Brand Marketing',
      'Content Marketing',
      'Digital Marketing',
      'Email Marketing',
      'Marketing Communications',
      'Marketing Research',
      'Partner Marketing',
      'Product Marketing',
      'Social Media Marketing',
      'All of the above',
    ],
  },
  {
    Professional_Field: 'Marketing',
    ID: 'MKT',
    value: [
      'General Marketing',
      'Brand Marketing',
      'Content Marketing',
      'Digital Marketing',
      'Email Marketing',
      'Marketing Communications',
      'Marketing Research',
      'Partner Marketing',
      'Product Marketing',
      'Social Media Marketing',
      'All of the above',
    ],
  },
  {
    Professional_Field: 'Marketing',
    ID: 'MKT',
    value: [
      'General Marketing',
      'Brand Marketing',
      'Content Marketing',
      'Digital Marketing',
      'Email Marketing',
      'Marketing Communications',
      'Marketing Research',
      'Partner Marketing',
      'Product Marketing',
      'Social Media Marketing',
      'All of the above',
    ],
  },
  {
    Professional_Field: 'Marketing',
    ID: 'MKT',
    value: [
      'General Marketing',
      'Brand Marketing',
      'Content Marketing',
      'Digital Marketing',
      'Email Marketing',
      'Marketing Communications',
      'Marketing Research',
      'Partner Marketing',
      'Product Marketing',
      'Social Media Marketing',
      'All of the above',
    ],
  },
  {
    Professional_Field: 'Marketing',
    ID: 'MKT',
    value: [
      'General Marketing',
      'Brand Marketing',
      'Content Marketing',
      'Digital Marketing',
      'Email Marketing',
      'Marketing Communications',
      'Marketing Research',
      'Partner Marketing',
      'Product Marketing',
      'Social Media Marketing',
      'All of the above',
    ],
  },
  {
    Professional_Field: 'Marketing',
    ID: 'MKT',
    value: [
      'General Marketing',
      'Brand Marketing',
      'Content Marketing',
      'Digital Marketing',
      'Email Marketing',
      'Marketing Communications',
      'Marketing Research',
      'Partner Marketing',
      'Product Marketing',
      'Social Media Marketing',
      'All of the above',
    ],
  },
  {
    Professional_Field: 'Marketing',
    ID: 'MKT',
    value: [
      'General Marketing',
      'Brand Marketing',
      'Content Marketing',
      'Digital Marketing',
      'Email Marketing',
      'Marketing Communications',
      'Marketing Research',
      'Partner Marketing',
      'Product Marketing',
      'Social Media Marketing',
      'All of the above',
    ],
  },
  {
    Professional_Field: 'Marketing',
    ID: 'MKT',
    value: [
      'General Marketing',
      'Brand Marketing',
      'Content Marketing',
      'Digital Marketing',
      'Email Marketing',
      'Marketing Communications',
      'Marketing Research',
      'Partner Marketing',
      'Product Marketing',
      'Social Media Marketing',
      'All of the above',
    ],
  },
  {
    Professional_Field: 'Marketing',
    ID: 'MKT',
    value: [
      'General Marketing',
      'Brand Marketing',
      'Content Marketing',
      'Digital Marketing',
      'Email Marketing',
      'Marketing Communications',
      'Marketing Research',
      'Partner Marketing',
      'Product Marketing',
      'Social Media Marketing',
      'All of the above',
    ],
  },
  {
    Professional_Field: 'Marketing',
    ID: 'MKT',
    value: [
      'General Marketing',
      'Brand Marketing',
      'Content Marketing',
      'Digital Marketing',
      'Email Marketing',
      'Marketing Communications',
      'Marketing Research',
      'Partner Marketing',
      'Product Marketing',
      'Social Media Marketing',
      'All of the above',
    ],
  },
  {
    Professional_Field: 'Marketing',
    ID: 'MKT',
    value: [
      'General Marketing',
      'Brand Marketing',
      'Content Marketing',
      'Digital Marketing',
      'Email Marketing',
      'Marketing Communications',
      'Marketing Research',
      'Partner Marketing',
      'Product Marketing',
      'Social Media Marketing',
      'All of the above',
    ],
  },
  {
    Professional_Field: 'Marketing',
    ID: 'MKT',
    value: [
      'General Marketing',
      'Brand Marketing',
      'Content Marketing',
      'Digital Marketing',
      'Email Marketing',
      'Marketing Communications',
      'Marketing Research',
      'Partner Marketing',
      'Product Marketing',
      'Social Media Marketing',
      'All of the above',
    ],
  },
  {
    Professional_Field: 'Marketing',
    ID: 'MKT',
    value: [
      'General Marketing',
      'Brand Marketing',
      'Content Marketing',
      'Digital Marketing',
      'Email Marketing',
      'Marketing Communications',
      'Marketing Research',
      'Partner Marketing',
      'Product Marketing',
      'Social Media Marketing',
      'All of the above',
    ],
  },
  {
    Professional_Field: 'Marketing',
    ID: 'MKT',
    value: [
      'General Marketing',
      'Brand Marketing',
      'Content Marketing',
      'Digital Marketing',
      'Email Marketing',
      'Marketing Communications',
      'Marketing Research',
      'Partner Marketing',
      'Product Marketing',
      'Social Media Marketing',
      'All of the above',
    ],
  },
  {
    Professional_Field: 'Marketing',
    ID: 'MKT',
    value: [
      'General Marketing',
      'Brand Marketing',
      'Content Marketing',
      'Digital Marketing',
      'Email Marketing',
      'Marketing Communications',
      'Marketing Research',
      'Partner Marketing',
      'Product Marketing',
      'Social Media Marketing',
      'All of the above',
    ],
  },
  {
    Professional_Field: 'Marketing',
    ID: 'MKT',
    value: [
      'General Marketing',
      'Brand Marketing',
      'Content Marketing',
      'Digital Marketing',
      'Email Marketing',
      'Marketing Communications',
      'Marketing Research',
      'Partner Marketing',
      'Product Marketing',
      'Social Media Marketing',
      'All of the above',
    ],
  },
  {
    Professional_Field: 'Marketing',
    ID: 'MKT',
    value: [
      'General Marketing',
      'Brand Marketing',
      'Content Marketing',
      'Digital Marketing',
      'Email Marketing',
      'Marketing Communications',
      'Marketing Research',
      'Partner Marketing',
      'Product Marketing',
      'Social Media Marketing',
      'All of the above',
    ],
  },
  {
    Professional_Field: 'Marketing',
    ID: 'MKT',
    value: [
      'General Marketing',
      'Brand Marketing',
      'Content Marketing',
      'Digital Marketing',
      'Email Marketing',
      'Marketing Communications',
      'Marketing Research',
      'Partner Marketing',
      'Product Marketing',
      'Social Media Marketing',
      'All of the above',
    ],
  },
  {
    Professional_Field: 'Marketing',
    ID: 'MKT',
    value: [
      'General Marketing',
      'Brand Marketing',
      'Content Marketing',
      'Digital Marketing',
      'Email Marketing',
      'Marketing Communications',
      'Marketing Research',
      'Partner Marketing',
      'Product Marketing',
      'Social Media Marketing',
      'All of the above',
    ],
  },
  {
    Professional_Field: 'Marketing',
    ID: 'MKT',
    value: [
      'General Marketing',
      'Brand Marketing',
      'Content Marketing',
      'Digital Marketing',
      'Email Marketing',
      'Marketing Communications',
      'Marketing Research',
      'Partner Marketing',
      'Product Marketing',
      'Social Media Marketing',
      'All of the above',
    ],
  },
  {
    Professional_Field: 'Marketing',
    ID: 'MKT',
    value: [
      'General Marketing',
      'Brand Marketing',
      'Content Marketing',
      'Digital Marketing',
      'Email Marketing',
      'Marketing Communications',
      'Marketing Research',
      'Partner Marketing',
      'Product Marketing',
      'Social Media Marketing',
      'All of the above',
    ],
  },
  {
    Professional_Field: 'Marketing',
    ID: 'MKT',
    value: [
      'General Marketing',
      'Brand Marketing',
      'Content Marketing',
      'Digital Marketing',
      'Email Marketing',
      'Marketing Communications',
      'Marketing Research',
      'Partner Marketing',
      'Product Marketing',
      'Social Media Marketing',
      'All of the above',
    ],
  },
  {
    Professional_Field: 'Marketing',
    ID: 'MKT',
    value: [
      'General Marketing',
      'Brand Marketing',
      'Content Marketing',
      'Digital Marketing',
      'Email Marketing',
      'Marketing Communications',
      'Marketing Research',
      'Partner Marketing',
      'Product Marketing',
      'Social Media Marketing',
      'All of the above',
    ],
  },
  {
    Professional_Field: 'Marketing',
    ID: 'MKT',
    value: [
      'General Marketing',
      'Brand Marketing',
      'Content Marketing',
      'Digital Marketing',
      'Email Marketing',
      'Marketing Communications',
      'Marketing Research',
      'Partner Marketing',
      'Product Marketing',
      'Social Media Marketing',
      'All of the above',
    ],
  },
  {
    Professional_Field: 'Marketing',
    ID: 'MKT',
    value: [
      'General Marketing',
      'Brand Marketing',
      'Content Marketing',
      'Digital Marketing',
      'Email Marketing',
      'Marketing Communications',
      'Marketing Research',
      'Partner Marketing',
      'Product Marketing',
      'Social Media Marketing',
      'All of the above',
    ],
  },
  {
    Professional_Field: 'Marketing',
    ID: 'MKT',
    value: [
      'General Marketing',
      'Brand Marketing',
      'Content Marketing',
      'Digital Marketing',
      'Email Marketing',
      'Marketing Communications',
      'Marketing Research',
      'Partner Marketing',
      'Product Marketing',
      'Social Media Marketing',
      'All of the above',
    ],
  },
  {
    Professional_Field: 'Marketing',
    ID: 'MKT',
    value: [
      'General Marketing',
      'Brand Marketing',
      'Content Marketing',
      'Digital Marketing',
      'Email Marketing',
      'Marketing Communications',
      'Marketing Research',
      'Partner Marketing',
      'Product Marketing',
      'Social Media Marketing',
      'All of the above',
    ],
  },
  {
    Professional_Field: 'Marketing',
    ID: 'MKT',
    value: [
      'General Marketing',
      'Brand Marketing',
      'Content Marketing',
      'Digital Marketing',
      'Email Marketing',
      'Marketing Communications',
      'Marketing Research',
      'Partner Marketing',
      'Product Marketing',
      'Social Media Marketing',
      'All of the above',
    ],
  },
  {
    Professional_Field: 'Marketing',
    ID: 'MKT',
    value: [
      'General Marketing',
      'Brand Marketing',
      'Content Marketing',
      'Digital Marketing',
      'Email Marketing',
      'Marketing Communications',
      'Marketing Research',
      'Partner Marketing',
      'Product Marketing',
      'Social Media Marketing',
      'All of the above',
    ],
  },
  {
    Professional_Field: 'Marketing',
    ID: 'MKT',
    value: [
      'General Marketing',
      'Brand Marketing',
      'Content Marketing',
      'Digital Marketing',
      'Email Marketing',
      'Marketing Communications',
      'Marketing Research',
      'Partner Marketing',
      'Product Marketing',
      'Social Media Marketing',
      'All of the above',
    ],
  },
  {
    Professional_Field: 'Marketing',
    ID: 'MKT',
    value: [
      'General Marketing',
      'Brand Marketing',
      'Content Marketing',
      'Digital Marketing',
      'Email Marketing',
      'Marketing Communications',
      'Marketing Research',
      'Partner Marketing',
      'Product Marketing',
      'Social Media Marketing',
      'All of the above',
    ],
  },
  {
    Professional_Field: 'Marketing',
    ID: 'MKT',
    value: [
      'General Marketing',
      'Brand Marketing',
      'Content Marketing',
      'Digital Marketing',
      'Email Marketing',
      'Marketing Communications',
      'Marketing Research',
      'Partner Marketing',
      'Product Marketing',
      'Social Media Marketing',
      'All of the above',
    ],
  },
  {
    Professional_Field: 'Marketing',
    ID: 'MKT',
    value: [
      'General Marketing',
      'Brand Marketing',
      'Content Marketing',
      'Digital Marketing',
      'Email Marketing',
      'Marketing Communications',
      'Marketing Research',
      'Partner Marketing',
      'Product Marketing',
      'Social Media Marketing',
      'All of the above',
    ],
  },
  {
    Professional_Field: 'Marketing',
    ID: 'MKT',
    value: [
      'General Marketing',
      'Brand Marketing',
      'Content Marketing',
      'Digital Marketing',
      'Email Marketing',
      'Marketing Communications',
      'Marketing Research',
      'Partner Marketing',
      'Product Marketing',
      'Social Media Marketing',
      'All of the above',
    ],
  },
  {
    Professional_Field: 'Marketing',
    ID: 'MKT',
    value: [
      'General Marketing',
      'Brand Marketing',
      'Content Marketing',
      'Digital Marketing',
      'Email Marketing',
      'Marketing Communications',
      'Marketing Research',
      'Partner Marketing',
      'Product Marketing',
      'Social Media Marketing',
      'All of the above',
    ],
  },
  {
    Professional_Field: 'Marketing',
    ID: 'MKT',
    value: [
      'General Marketing',
      'Brand Marketing',
      'Content Marketing',
      'Digital Marketing',
      'Email Marketing',
      'Marketing Communications',
      'Marketing Research',
      'Partner Marketing',
      'Product Marketing',
      'Social Media Marketing',
      'All of the above',
    ],
  },
  {
    Professional_Field: 'Marketing',
    ID: 'MKT',
    value: [
      'General Marketing',
      'Brand Marketing',
      'Content Marketing',
      'Digital Marketing',
      'Email Marketing',
      'Marketing Communications',
      'Marketing Research',
      'Partner Marketing',
      'Product Marketing',
      'Social Media Marketing',
      'All of the above',
    ],
  },
  {
    Professional_Field: 'Marketing',
    ID: 'MKT',
    value: [
      'General Marketing',
      'Brand Marketing',
      'Content Marketing',
      'Digital Marketing',
      'Email Marketing',
      'Marketing Communications',
      'Marketing Research',
      'Partner Marketing',
      'Product Marketing',
      'Social Media Marketing',
      'All of the above',
    ],
  },
  {
    Professional_Field: 'Marketing',
    ID: 'MKT',
    value: [
      'General Marketing',
      'Brand Marketing',
      'Content Marketing',
      'Digital Marketing',
      'Email Marketing',
      'Marketing Communications',
      'Marketing Research',
      'Partner Marketing',
      'Product Marketing',
      'Social Media Marketing',
      'All of the above',
    ],
  },
  {
    Professional_Field: 'Marketing',
    ID: 'MKT',
    value: [
      'General Marketing',
      'Brand Marketing',
      'Content Marketing',
      'Digital Marketing',
      'Email Marketing',
      'Marketing Communications',
      'Marketing Research',
      'Partner Marketing',
      'Product Marketing',
      'Social Media Marketing',
      'All of the above',
    ],
  },
  {
    Professional_Field: 'Marketing',
    ID: 'MKT',
    value: [
      'General Marketing',
      'Brand Marketing',
      'Content Marketing',
      'Digital Marketing',
      'Email Marketing',
      'Marketing Communications',
      'Marketing Research',
      'Partner Marketing',
      'Product Marketing',
      'Social Media Marketing',
      'All of the above',
    ],
  },
  {
    Professional_Field: 'Marketing',
    ID: 'MKT',
    value: [
      'General Marketing',
      'Brand Marketing',
      'Content Marketing',
      'Digital Marketing',
      'Email Marketing',
      'Marketing Communications',
      'Marketing Research',
      'Partner Marketing',
      'Product Marketing',
      'Social Media Marketing',
      'All of the above',
    ],
  },
  {
    Professional_Field: 'Marketing',
    ID: 'MKT',
    value: [
      'General Marketing',
      'Brand Marketing',
      'Content Marketing',
      'Digital Marketing',
      'Email Marketing',
      'Marketing Communications',
      'Marketing Research',
      'Partner Marketing',
      'Product Marketing',
      'Social Media Marketing',
      'All of the above',
    ],
  },
  {
    Professional_Field: 'Marketing',
    ID: 'MKT',
    value: [
      'General Marketing',
      'Brand Marketing',
      'Content Marketing',
      'Digital Marketing',
      'Email Marketing',
      'Marketing Communications',
      'Marketing Research',
      'Partner Marketing',
      'Product Marketing',
      'Social Media Marketing',
      'All of the above',
    ],
  },
  {
    Professional_Field: 'Marketing',
    ID: 'MKT',
    value: [
      'General Marketing',
      'Brand Marketing',
      'Content Marketing',
      'Digital Marketing',
      'Email Marketing',
      'Marketing Communications',
      'Marketing Research',
      'Partner Marketing',
      'Product Marketing',
      'Social Media Marketing',
      'All of the above',
    ],
  },
  {
    Professional_Field: 'Marketing',
    ID: 'MKT',
    value: [
      'General Marketing',
      'Brand Marketing',
      'Content Marketing',
      'Digital Marketing',
      'Email Marketing',
      'Marketing Communications',
      'Marketing Research',
      'Partner Marketing',
      'Product Marketing',
      'Social Media Marketing',
      'All of the above',
    ],
  },
  {
    Professional_Field: 'Marketing',
    ID: 'MKT',
    value: [
      'General Marketing',
      'Brand Marketing',
      'Content Marketing',
      'Digital Marketing',
      'Email Marketing',
      'Marketing Communications',
      'Marketing Research',
      'Partner Marketing',
      'Product Marketing',
      'Social Media Marketing',
      'All of the above',
    ],
  },
  {
    Professional_Field: 'Marketing',
    ID: 'MKT',
    value: [
      'General Marketing',
      'Brand Marketing',
      'Content Marketing',
      'Digital Marketing',
      'Email Marketing',
      'Marketing Communications',
      'Marketing Research',
      'Partner Marketing',
      'Product Marketing',
      'Social Media Marketing',
      'All of the above',
    ],
  },
];
